# Generated by Django 3.0.7 on 2022-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offender',
            name='offender',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='victim',
            name='victim',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
