# Generated by Django 3.0.7 on 2022-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_auto_20220526_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='after',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='before',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
