# Generated by Django 3.0.7 on 2022-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_auto_20220526_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offender',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
