# Generated by Django 3.2.13 on 2022-05-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0006_alter_victim_crimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victim',
            old_name='crimes',
            new_name='id_crimes',
        ),
    ]
